-- --------------------------------------------------------
-- Host:                         emcosoft.com.co
-- Versión del servidor:         5.7.44 - MySQL Community Server (GPL)
-- SO del servidor:              Linux
-- HeidiSQL Versión:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Volcando datos para la tabla emcosoft_db.compensation_funds: ~43 rows (aproximadamente)
INSERT IGNORE INTO `compensation_funds` (`name`, `code`, `nit`, `created_at`, `updated_at`, `status`) VALUES
	('CAJA DE COMPENSACIÓN FAMILIAR CAMACOL  COMFAMILIAR CAMACOL', 'CCF02', '890900840-1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR COMFENALCO ANTIOQUIA', 'CCF03', '890900842-6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE ANTIOQUIA COMFAMA', 'CCF04', '890900841-9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR CAJACOPI ATLANTICO', 'CCF05', '890102044-1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE BARRANQUILLA COMBARRANQUILLA', 'CCF06', '890102002-2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR COMFAMILIAR DEL ATLANTICO', 'CCF07', '890101994-9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE FENALCO  - ANDI COMFENALCO CARTAGENA', 'CCF08', '890480023-7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE CARTAGENA', 'CCF09', '890480110', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE BOYACA - COMFABOY', 'CCF10', '891800213', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE CALDAS', 'CCF11', '890806490-5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DEL CAQUETÁ - COMFACA', 'CCF13', '817000499-5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DEL CAUCA - COMFACAUCA', 'CCF14', '891500182-0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACION FAMILIAR DEL CESAR COMFACESAR', 'CCF15', '892399989-8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE CORDOBA COMFACOR', 'CCF16', '891080005', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR CAFAM', 'CCF21', '860013570-3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA COLOMBIANA DE SUBSIDIO FAMILIAR COLSUBSIDIO', 'CCF22', '860007336-1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR COMPENSAR', 'CCF24', '860066942-7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE CUNDINAMARCA - COMFACUNDI', 'CCF26', '860045904-7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DEL CHOCÓ', 'CCF29', '891600091-8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE LA GUAJIRA', 'CCF30', '892115006-5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DEL HUILA - COMFAMILIAR', 'CCF32', '891180008-2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DEL MAGDALENA', 'CCF33', '891780093-3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR REGIONAL DEL META COFREM', 'CCF34', '892000146-3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE NARIÑO', 'CCF35', '891280008-1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DEL ORIENTE COLOMBIANO COMFAORIENTE', 'CCF36', '890500675-6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DEL NORTE DE SANTANDER COMFANORTE', 'CCF37', '890500516-3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE BARRANCABERMEJA CAFABA', 'CCF38', '890270275-5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA SANTANDEREANA DE SUBSIDIO FAMILIAR CAJASAN', 'CCF39', '890200106-1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR COMFENALCO SANTANDER', 'CCF40', '890201578-7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE SUCRE', 'CCF41', '892200015-5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE FENALCO COMFENALCO QUINDIO', 'CCF43', '890000381-0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE RISARALDA - COMFAMILIAR RISARALDA', 'CCF44', '891480000-1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DEL SUR DEL TOLIMA CAFASUR', 'CCF46', '890704737-0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE FENALCO DEL TOLIMA - COMFENALCO', 'CCF50', '890700148-4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR COMFENALCO DEL VALLE DEL CAUCA - COMFENALCO VALLE', 'CCF56', '890303093', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DEL VALLE DEL CAUCA COMFAMILIAR ANDI - COMFANDI', 'CCF57', '890303208-5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DEL PUTUMAYO - COMFAMILIAR PUTUMAYO', 'CCF63', '891200337-8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE SAN ANDRES Y PROVIDENCIA, ISLAS CAJASAI', 'CCF64', '892400320-5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DEL AMAZONAS CAFAMAZ', 'CCF65', '800003122-6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DE ARAUCA COMFIAR', 'CCF67', '800219488-4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR CAMPESINA COMCAJA', 'CCF68', '800231969-4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACIÓN FAMILIAR DEL CASANARE - COMFACASANARE', 'CCF69', '844003392-8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Activo'),
	('CAJA DE COMPENSACION FAMILIAR DEL TOLIMA COMFATOLIMA', 'CCF48', '800211025-1', NULL, NULL, 'Activo');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
