-- --------------------------------------------------------
-- Host:                         emcosoft.com.co
-- Versión del servidor:         5.7.44 - MySQL Community Server (GPL)
-- SO del servidor:              Linux
-- HeidiSQL Versión:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Volcando datos para la tabla emcosoft_db.departments: ~33 rows (aproximadamente)
INSERT IGNORE INTO `departments` (`name`, `code`, `created_at`, `updated_at`, `country_id`, `dian_code`, `dane_code`) VALUES
	('ANTIOQUIA', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('ATLÁNTICO', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('BOGOTÁ, D.C.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('BOLÍVAR', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('BOYACÁ', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('CALDAS', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('CAQUETÁ', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('CAUCA', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('CESAR', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('CÓRDOBA', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('CUNDINAMARCA', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('CHOCÓ', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('HUILA', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('LA GUAJIRA', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('MAGDALENA', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('META', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('NARIÑO', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('NORTE DE SANTANDER', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('QUINDIO', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('RISARALDA', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('SANTANDER', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('SUCRE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('TOLIMA', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('VALLE DEL CAUCA', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('ARAUCA', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('CASANARE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('PUTUMAYO', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('AMAZONAS', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('GUAINÍA', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('GUAVIARE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('VAUPÉS', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL),
	('VICHADA', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, NULL, NULL);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
