INSERT IGNORE INTO `municipalities` (`department_id`, `name`, `code`, `municipalities_id`, `abbreviation`, `dian_code`, `dane_code`, `state`) VALUES
(5, 'Abriaquí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Acacías', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Acandí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Acevedo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Achí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Agrado', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Agua de Dios', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Aguachica', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Aguada', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Aguadas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Aguazul', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Agustín Codazzi', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Aipe', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'Albania', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'Albania', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Albania', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Albán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Albán (San José)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Alcalá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Alejandria', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Algarrobo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Algeciras', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Almaguer', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Almeida', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Alpujarra', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Altamira', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Alto Baudó (Pie de Pato)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Altos del Rosario', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Alvarado', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Amagá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Amalfi', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Ambalema', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Anapoima', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Ancuya', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Andalucía', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Andes', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Angelópolis', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Angostura', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Anolaima', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Anorí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Anserma', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Ansermanuevo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Anzoátegui', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Anzá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Apartadó', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Apulo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(66, 'Apía', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Aquitania', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Aracataca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Aranzazu', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Aratoca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(81, 'Arauca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(81, 'Arauquita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Arbeláez', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Arboleda (Berruecos)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Arboledas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Arboletes', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Arcabuco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Arenal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Argelia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Argelia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Argelia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Ariguaní (El Difícil)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Arjona', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Armenia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(63, 'Armenia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Armero (Guayabal)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Arroyohondo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Astrea', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Ataco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Atrato (Yuto)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Ayapel', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Bagadó', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Bahía Solano (Mútis)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Bajo Baudó (Pizarro)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Balboa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(66, 'Balboa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Baranoa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Baraya', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Barbacoas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Barbosa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Barbosa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Barichara', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Barranca de Upía', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Barrancabermeja', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'Barrancas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Barranco de Loba', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Barranquilla', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Becerríl', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Belalcázar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Bello', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Belmira', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Beltrán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Belén', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Belén', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Belén de Bajirá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(66, 'Belén de Umbría', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'Belén de los Andaquíes', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Berbeo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Betania', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Beteitiva', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Betulia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Betulia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Bituima', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Boavita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Bochalema', NULL, 0, NULL, NULL, NULL, 'Activo'),
(11, 'Bogotá D.C.', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Bojacá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Bojayá (Bellavista)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Bolívar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Bolívar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Bolívar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Bolívar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Bosconia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Boyacá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Briceño', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Briceño', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Bucaramanga', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Bucarasica', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Buenaventura', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Buenavista', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Buenavista', NULL, 0, NULL, NULL, NULL, 'Activo'),
(63, 'Buenavista', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Buenavista', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Buenos Aires', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Buesaco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Buga', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Bugalagrande', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Burítica', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Busbanza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Cabrera', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Cabrera', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Cabuyaro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Cachipay', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Caicedo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Caicedonia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Caimito', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Cajamarca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Cajibío', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Cajicá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Calamar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(95, 'Calamar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(63, 'Calarcá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Caldas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Caldas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Caldono', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'California', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Calima (Darién)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Caloto', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Calí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Campamento', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Campo de la Cruz', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Campoalegre', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Campohermoso', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Canalete', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Candelaria', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Candelaria', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Cantagallo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Cantón de San Pablo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Caparrapí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Capitanejo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Caracolí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Caramanta', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Carcasí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Carepa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Carmen de Apicalá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Carmen de Carupa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Carmen de Viboral', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Carmen del Darién (CURBARADÓ)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Carolina', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Cartagena', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'Cartagena del Chairá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Cartago', NULL, 0, NULL, NULL, NULL, 'Activo'),
(97, 'Carurú', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Casabianca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Castilla la Nueva', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Caucasia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Cañasgordas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Cepita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Cereté', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Cerinza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Cerrito', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Cerro San Antonio', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Chachaguí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Chaguaní', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Chalán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Chaparral', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Charalá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Charta', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Chigorodó', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Chima', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Chimichagua', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Chimá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Chinavita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Chinchiná', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Chinácota', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Chinú', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Chipaque', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Chipatá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Chiquinquirá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Chiriguaná', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Chiscas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Chita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Chitagá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Chitaraque', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Chivatá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Chivolo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Choachí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Chocontá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Chámeza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Chía', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Chíquiza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Chívor', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Cicuco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Cimitarra', NULL, 0, NULL, NULL, NULL, 'Activo'),
(63, 'Circasia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Cisneros', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Ciénaga', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Ciénaga', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Ciénaga de Oro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Clemencia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Cocorná', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Coello', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Cogua', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Colombia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Colosó (Ricaurte)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(86, 'Colón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Colón (Génova)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Concepción', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Concepción', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Concordia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Concordia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Condoto', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Confines', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Consaca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Contadero', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Contratación', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Convención', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Copacabana', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Coper', NULL, 0, NULL, NULL, NULL, 'Activo'),
(63, 'Cordobá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Corinto', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Coromoro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Corozal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Corrales', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Cota', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Cotorra', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Covarachía', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Coveñas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Coyaima', NULL, 0, NULL, NULL, NULL, 'Activo'),
(81, 'Cravo Norte', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Cuaspud (Carlosama)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Cubarral', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Cubará', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Cucaita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Cucunubá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Cucutilla', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Cuitiva', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Cumaral', NULL, 0, NULL, NULL, NULL, 'Activo'),
(99, 'Cumaribo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Cumbal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Cumbitara', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Cunday', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'Curillo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Curití', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Curumaní', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Cáceres', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Cáchira', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Cácota', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Cáqueza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Cértegui', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Cómbita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Córdoba', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Córdoba', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Cúcuta', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Dabeiba', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Dagua', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'Dibulla', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'Distracción', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Dolores', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Don Matías', NULL, 0, NULL, NULL, NULL, 'Activo'),
(66, 'Dos Quebradas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Duitama', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Durania', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Ebéjico', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'El Bagre', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'El Banco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'El Cairo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'El Calvario', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'El Carmen', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'El Carmen', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'El Carmen de Atrato', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'El Carmen de Bolívar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'El Castillo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'El Cerrito', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'El Charco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'El Cocuy', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'El Colegio', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'El Copey', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'El Doncello', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'El Dorado', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'El Dovio', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'El Espino', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'El Guacamayo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'El Guamo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'El Molino', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'El Paso', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'El Paujil', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'El Peñol', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'El Peñon', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'El Peñon', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'El Peñón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'El Piñon', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'El Playón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(95, 'El Retorno', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'El Retén', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'El Roble', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'El Rosal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'El Rosario', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'El Tablón de Gómez', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'El Tambo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'El Tambo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'El Tarra', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'El Zulia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'El Águila', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Elías', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Encino', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Enciso', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Entrerríos', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Envigado', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Espinal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Facatativá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Falan', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Filadelfia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(63, 'Filandia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Firavitoba', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Flandes', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'Florencia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Florencia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Floresta', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Florida', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Floridablanca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Florián', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'Fonseca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(81, 'Fortúl', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Fosca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Francisco Pizarro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Fredonia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Fresno', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Frontino', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Fuente de Oro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Fundación', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Funes', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Funza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Fusagasugá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Fómeque', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Fúquene', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Gachalá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Gachancipá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Gachantivá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Gachetá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Galapa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Galeras (Nueva Granada)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Galán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Gama', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Gamarra', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Garagoa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Garzón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Gigante', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Ginebra', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Giraldo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Girardot', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Girardota', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Girón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Gonzalez', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Gramalote', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Granada', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Granada', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Granada', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Guaca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Guacamayas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Guacarí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Guachavés', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Guachené', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Guachetá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Guachucal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Guadalupe', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Guadalupe', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Guadalupe', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Guaduas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Guaitarilla', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Gualmatán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Guamal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Guamal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Guamo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Guapota', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Guapí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Guaranda', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Guarne', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Guasca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Guatapé', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Guataquí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Guatavita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Guateque', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Guavatá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Guayabal de Siquima', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Guayabetal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Guayatá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Guepsa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Guicán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Gutiérrez', NULL, 0, NULL, NULL, NULL, 'Activo'),
(66, 'Guática', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Gámbita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Gámeza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(63, 'Génova', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Gómez Plata', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Hacarí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Hatillo de Loba', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Hato', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Hato Corozal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'Hatonuevo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Heliconia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Herrán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Herveo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Hispania', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Hobo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Honda', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Ibagué', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Icononzo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Iles', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Imúes', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Inzá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(94, 'Inírida', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Ipiales', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Isnos', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Istmina', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Itagüí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Ituango', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Izá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Jambaló', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Jamundí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Jardín', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Jenesano', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Jericó', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Jericó', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Jerusalén', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Jesús María', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Jordán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Juan de Acosta', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Junín', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Juradó', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'La Apartada y La Frontera', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'La Argentina', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'La Belleza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'La Calera', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'La Capilla', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'La Ceja', NULL, 0, NULL, NULL, NULL, 'Activo'),
(66, 'La Celia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'La Cruz', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'La Cumbre', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'La Dorada', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'La Esperanza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'La Estrella', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'La Florida', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'La Gloria', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'La Jagua de Ibirico', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'La Jagua del Pilar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'La Llanada', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'La Macarena', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'La Merced', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'La Mesa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'La Montañita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'La Palma', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'La Paz', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'La Paz (Robles)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'La Peña', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'La Pintada', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'La Plata', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'La Playa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(99, 'La Primavera', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'La Salina', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'La Sierra', NULL, 0, NULL, NULL, NULL, 'Activo'),
(63, 'La Tebaida', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'La Tola', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'La Unión', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'La Unión', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'La Unión', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'La Unión', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'La Uvita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'La Vega', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'La Vega', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'La Victoria', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'La Victoria', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'La Victoria', NULL, 0, NULL, NULL, NULL, 'Activo'),
(66, 'La Virginia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Labateca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Labranzagrande', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Landázuri', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Lebrija', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Leiva', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Lejanías', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Lenguazaque', NULL, 0, NULL, NULL, NULL, 'Activo'),
(91, 'Leticia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Liborina', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Linares', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Lloró', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Lorica', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Los Córdobas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Los Palmitos', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Los Patios', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Los Santos', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Lourdes', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Luruaco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Lérida', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Líbano', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'López (Micay)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Macanal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Macaravita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Maceo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Machetá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Madrid', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Magangué', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Magüi (Payán)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Mahates', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'Maicao', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Majagual', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Malambo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Mallama (Piedrancha)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Manatí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'Manaure', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Manaure Balcón del Cesar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Manizales', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Manta', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Manzanares', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Maní', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Mapiripan', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Margarita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Marinilla', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Maripí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Mariquita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Marmato', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Marquetalia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(66, 'Marsella', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Marulanda', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'María la Baja', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Matanza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Medellín', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Medina', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Medio Atrato', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Medio Baudó', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Medio San Juan (ANDAGOYA)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Melgar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Mercaderes', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Mesetas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'Milán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Miraflores', NULL, 0, NULL, NULL, NULL, 'Activo'),
(95, 'Miraflores', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Miranda', NULL, 0, NULL, NULL, NULL, 'Activo'),
(66, 'Mistrató', NULL, 0, NULL, NULL, NULL, 'Activo'),
(97, 'Mitú', NULL, 0, NULL, NULL, NULL, 'Activo'),
(86, 'Mocoa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Mogotes', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Molagavita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Momil', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Mompós', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Mongua', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Monguí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Moniquirá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Montebello', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Montecristo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Montelíbano', NULL, 0, NULL, NULL, NULL, 'Activo'),
(63, 'Montenegro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Monteria', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Monterrey', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Morales', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Morales', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'Morelia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Morroa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Mosquera', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Mosquera', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Motavita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Moñitos', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Murillo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Murindó', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Mutatá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Mutiscua', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Muzo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Málaga', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Nariño', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Nariño', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Nariño', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Natagaima', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Nechí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Necoclí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Neira', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Neiva', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Nemocón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Nilo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Nimaima', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Nobsa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Nocaima', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Norcasia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Norosí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Novita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Nueva Granada', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Nuevo Colón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Nunchía', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Nuquí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Nátaga', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Obando', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Ocamonte', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Ocaña', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Oiba', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Oicatá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Olaya', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Olaya Herrera', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Onzaga', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Oporapa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(86, 'Orito', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Orocué', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Ortega', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Ospina', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Otanche', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Ovejas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Pachavita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Pacho', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Padilla', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Paicol', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Pailitas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Paime', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Paipa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Pajarito', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Palermo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Palestina', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Palestina', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Palmar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Palmar de Varela', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Palmas del Socorro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Palmira', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Palmito', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Palocabildo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Pamplona', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Pamplonita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Pandi', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Panqueba', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Paratebueno', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Pasca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Patía (El Bordo)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Pauna', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Paya', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Paz de Ariporo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Paz de Río', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Pedraza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Pelaya', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Pensilvania', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Peque', NULL, 0, NULL, NULL, NULL, 'Activo'),
(66, 'Pereira', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Pesca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Peñol', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Piamonte', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Pie de Cuesta', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Piedras', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Piendamó', NULL, 0, NULL, NULL, NULL, 'Activo'),
(63, 'Pijao', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Pijiño', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Pinchote', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Pinillos', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Piojo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Pisva', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Pital', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Pitalito', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Pivijay', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Planadas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Planeta Rica', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Plato', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Policarpa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Polonuevo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Ponedera', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Popayán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Pore', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Potosí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Pradera', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Prado', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Providencia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(88, 'Providencia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Pueblo Bello', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Pueblo Nuevo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(66, 'Pueblo Rico', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Pueblorrico', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Puebloviejo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Puente Nacional', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Puerres', NULL, 0, NULL, NULL, NULL, 'Activo'),
(86, 'Puerto Asís', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Puerto Berrío', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Puerto Boyacá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(86, 'Puerto Caicedo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(99, 'Puerto Carreño', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Puerto Colombia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Puerto Concordia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Puerto Escondido', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Puerto Gaitán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(86, 'Puerto Guzmán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(86, 'Puerto Leguízamo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Puerto Libertador', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Puerto Lleras', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Puerto López', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Puerto Nare', NULL, 0, NULL, NULL, NULL, 'Activo'),
(91, 'Puerto Nariño', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Puerto Parra', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'Puerto Rico', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Puerto Rico', NULL, 0, NULL, NULL, NULL, 'Activo'),
(81, 'Puerto Rondón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Puerto Salgar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Puerto Santander', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Puerto Tejada', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Puerto Triunfo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Puerto Wilches', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Pulí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Pupiales', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Puracé (Coconuco)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Purificación', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Purísima', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Pácora', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Páez', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Páez (Belalcazar)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Páramo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Quebradanegra', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Quetame', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Quibdó', NULL, 0, NULL, NULL, NULL, 'Activo'),
(63, 'Quimbaya', NULL, 0, NULL, NULL, NULL, 'Activo'),
(66, 'Quinchía', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Quipama', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Quipile', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Ragonvalia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Ramiriquí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Recetor', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Regidor', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Remedios', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Remolino', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Repelón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Restrepo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Restrepo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Retiro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Ricaurte', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Ricaurte', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Rio Negro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Rioblanco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Riofrío', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'Riohacha', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Risaralda', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Rivera', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Roberto Payán (San José)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Roldanillo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Roncesvalles', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Rondón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Rosas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Rovira', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Ráquira', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Río Iró', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Río Quito', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Río Sucio', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Río Viejo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Río de oro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Ríonegro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Ríosucio', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Sabana de Torres', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Sabanagrande', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Sabanalarga', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Sabanalarga', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Sabanalarga', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Sabanas de San Angel (SAN ANGEL)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Sabaneta', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Saboyá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Sahagún', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Saladoblanco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Salamina', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Salamina', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Salazar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Saldaña', NULL, 0, NULL, NULL, NULL, 'Activo'),
(63, 'Salento', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Salgar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Samacá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Samaniego', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Samaná', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Sampués', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'San Agustín', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'San Alberto', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'San Andrés', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'San Andrés Sotavento', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'San Andrés de Cuerquía', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'San Antero', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'San Antonio', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'San Antonio de Tequendama', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'San Benito', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'San Benito Abad', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'San Bernardo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'San Bernardo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'San Bernardo del Viento', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'San Calixto', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'San Carlos', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'San Carlos', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'San Carlos de Guaroa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'San Cayetano', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'San Cayetano', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'San Cristobal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'San Diego', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'San Eduardo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'San Estanislao', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'San Fernando', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'San Francisco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'San Francisco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(86, 'San Francisco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'San Gíl', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'San Jacinto', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'San Jacinto del Cauca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'San Jerónimo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'San Joaquín', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'San José', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'San José de Miranda', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'San José de Montaña', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'San José de Pare', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'San José de Uré', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'San José del Fragua', NULL, 0, NULL, NULL, NULL, 'Activo'),
(95, 'San José del Guaviare', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'San José del Palmar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'San Juan de Arama', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'San Juan de Betulia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'San Juan de Nepomuceno', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'San Juan de Pasto', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'San Juan de Río Seco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'San Juan de Urabá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'San Juan del Cesar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'San Juanito', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'San Lorenzo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'San Luis', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'San Luís', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'San Luís de Gaceno', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'San Luís de Palenque', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'San Marcos', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'San Martín', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'San Martín', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'San Martín de Loba', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'San Mateo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'San Miguel', NULL, 0, NULL, NULL, NULL, 'Activo'),
(86, 'San Miguel', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'San Miguel de Sema', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'San Onofre', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'San Pablo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'San Pablo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'San Pablo de Borbur', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'San Pedro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'San Pedro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'San Pedro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'San Pedro de Cartago', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'San Pedro de Urabá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'San Pelayo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'San Rafael', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'San Roque', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'San Sebastián', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'San Sebastián de Buenavista', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'San Vicente', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'San Vicente del Caguán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'San Vicente del Chucurí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'San Zenón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Sandoná', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Santa Ana', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Santa Bárbara', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Santa Bárbara', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Santa Bárbara (Iscuandé)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Santa Bárbara de Pinto', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Santa Catalina', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Santa Fé de Antioquia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Santa Genoveva de Docorodó', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Santa Helena del Opón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Santa Isabel', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Santa Lucía', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Santa Marta', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Santa María', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Santa María', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Santa Rosa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Santa Rosa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(66, 'Santa Rosa de Cabal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Santa Rosa de Osos', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Santa Rosa de Viterbo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Santa Rosa del Sur', NULL, 0, NULL, NULL, NULL, 'Activo'),
(99, 'Santa Rosalía', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Santa Sofía', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Santana', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Santander de Quilichao', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Santiago', NULL, 0, NULL, NULL, NULL, 'Activo'),
(86, 'Santiago', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Santo Domingo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Santo Tomás', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Santuario', NULL, 0, NULL, NULL, NULL, 'Activo'),
(66, 'Santuario', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Sapuyes', NULL, 0, NULL, NULL, NULL, 'Activo'),
(81, 'Saravena', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Sardinata', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Sasaima', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Sativanorte', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Sativasur', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Segovia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Sesquilé', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Sevilla', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Siachoque', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Sibaté', NULL, 0, NULL, NULL, NULL, 'Activo'),
(86, 'Sibundoy', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Silos', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Silvania', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Silvia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Simacota', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Simijaca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Simití', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Sincelejo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Sincé', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Sipí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Sitionuevo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Soacha', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Soatá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Socha', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Socorro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Socotá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Sogamoso', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'Solano', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Soledad', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'Solita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Somondoco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Sonsón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Sopetrán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Soplaviento', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Sopó', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Sora', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Soracá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Sotaquirá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Sotara (Paispamba)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Sotomayor (Los Andes)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Suaita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Suan', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Suaza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Subachoque', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Sucre', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Sucre', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Sucre', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Suesca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Supatá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Supía', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Suratá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Susa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Susacón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Sutamarchán', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Sutatausa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Sutatenza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Suárez', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Suárez', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Sácama', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Sáchica', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Tabio', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Tadó', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Talaigua Nuevo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Tamalameque', NULL, 0, NULL, NULL, NULL, 'Activo'),
(81, 'Tame', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Taminango', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Tangua', NULL, 0, NULL, NULL, NULL, 'Activo'),
(97, 'Taraira', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Tarazá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Tarqui', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Tarso', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Tasco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Tauramena', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Tausa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Tello', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Tena', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Tenerife', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Tenjo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Tenza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Teorama', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Teruel', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Tesalia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Tibacuy', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Tibaná', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Tibasosa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Tibirita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Tibú', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Tierralta', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Timaná', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Timbiquí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Timbío', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Tinjacá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Tipacoque', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Tiquisio (Puerto Rico)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Titiribí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Toca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Tocaima', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Tocancipá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Toguí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Toledo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Toledo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Tolú', NULL, 0, NULL, NULL, NULL, 'Activo'),
(70, 'Tolú Viejo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Tona', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Topagá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Topaipí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Toribío', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Toro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Tota', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Totoró', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Trinidad', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Trujillo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Tubará', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Tuchín', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Tulúa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Tumaco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Tunja', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Tunungua', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Turbaco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Turbaná', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Turbo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Turmequé', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Tuta', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Tutasá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Támara', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Támesis', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Túquerres', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Ubalá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Ubaque', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Ubaté', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Ulloa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Une', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Unguía', NULL, 0, NULL, NULL, NULL, 'Activo'),
(27, 'Unión Panamericana (ÁNIMAS)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Uramita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Uribe', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'Uribia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Urrao', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'Urumita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(8, 'Usiacuri', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Valdivia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(23, 'Valencia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Valle de San José', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Valle de San Juan', NULL, 0, NULL, NULL, NULL, 'Activo'),
(86, 'Valle del Guamuez', NULL, 0, NULL, NULL, NULL, 'Activo'),
(20, 'Valledupar', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Valparaiso', NULL, 0, NULL, NULL, NULL, 'Activo'),
(18, 'Valparaiso', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Vegachí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Venadillo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Venecia', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Venecia (Ospina Pérez)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Ventaquemada', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Vergara', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Versalles', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Vetas', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Viani', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Vigía del Fuerte', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Vijes', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Villa Caro', NULL, 0, NULL, NULL, NULL, 'Activo'),
(19, 'Villa Rica', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Villa de Leiva', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Villa del Rosario', NULL, 0, NULL, NULL, NULL, 'Activo'),
(86, 'Villagarzón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Villagómez', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Villahermosa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Villamaría', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Villanueva', NULL, 0, NULL, NULL, NULL, 'Activo'),
(44, 'Villanueva', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Villanueva', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Villanueva', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Villapinzón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(73, 'Villarrica', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Villavicencio', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Villavieja', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Villeta', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Viotá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Viracachá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(50, 'Vista Hermosa', NULL, 0, NULL, NULL, NULL, 'Activo'),
(17, 'Viterbo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Vélez', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Yacopí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(52, 'Yacuanquer', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Yaguará', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Yalí', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Yarumal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Yolombó', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Yondó (Casabe)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(85, 'Yopal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Yotoco', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Yumbo', NULL, 0, NULL, NULL, NULL, 'Activo'),
(13, 'Zambrano', NULL, 0, NULL, NULL, NULL, 'Activo'),
(68, 'Zapatoca', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Zapayán (PUNTA DE PIEDRAS)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(5, 'Zaragoza', NULL, 0, NULL, NULL, NULL, 'Activo'),
(76, 'Zarzal', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Zetaquirá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Zipacón', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Zipaquirá', NULL, 0, NULL, NULL, NULL, 'Activo'),
(47, 'Zona Bananera (PRADO - SEVILLA)', NULL, 0, NULL, NULL, NULL, 'Activo'),
(54, 'Ábrego', NULL, 0, NULL, NULL, NULL, 'Activo'),
(41, 'Íquira', NULL, 0, NULL, NULL, NULL, 'Activo'),
(15, 'Úmbita', NULL, 0, NULL, NULL, NULL, 'Activo'),
(25, 'Útica', NULL, 0, NULL, NULL, NULL, 'Activo');